version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build:
      context: ./services  
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ui
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
