version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}       
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
      POSTGRES_DB: ${DB_NAME}           
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    # build:  # for local deploy
    #   context: ./services  
    #   dockerfile: Dockerfile
    image: shlok08/services:v2
    restart: always
    depends_on:
      db : 
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3001:3001"

  frontend:
    # build:   # for local deploy
    #   context: ui
    #   dockerfile: Dockerfile
    image: shlok08/commerceapiui:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
