apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: commerce
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          ports:
            - containerPort: 3001
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: commerce-config
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: commerce-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: commerce-config
                  key: DB_PORT
            - name: DB_USER
              value: {{ .Values.secrets.dbUser }}
            - name: DB_PASSWORD
              value: {{ .Values.secrets.dbPassword }}
            - name: JWT_SECRET
              value: {{ .Values.secrets.jwtSecret }}
