apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.db.image }}:{{ .Values.db.tag }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "userdb"
            - name: POSTGRES_USER
              value: {{ .Values.secrets.dbUser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.secrets.dbPassword }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
