apiVersion: v1
kind: Secret
metadata:
  name: commerce-secrets
  namespace: commerce
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.dbUser }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
